In [1]:
import lancedb
from dotenv import load_dotenv

load_dotenv()

db = lancedb.connect(uri = "../knowledge_base")
db

LanceDBConnection(uri='c:\\Users\\tasmi\\MLOPS\\RAG_mlops25\\rag\\src\\rag\\exploration\\..\\knowledge_base')

In [2]:
db["articles"]

LanceTable(name='articles', version=11, _conn=LanceDBConnection(uri='c:\\Users\\tasmi\\MLOPS\\RAG_mlops25\\rag\\src\\rag\\exploration\\..\\knowledge_base'))

In [3]:
db["articles"].to_pandas()

,document_name,filepath,content,embedding
0,fisk (1).txt,C:\Users\tasmi\mlops\RAG_mlops25\rag\src\rag\d...,Fiskar (Pisces) är en grupp vattenlevande rygg...,"[0.05697632, 0.020736694, -0.028640747, -0.049..."
1,kanin (1).txt,C:\Users\tasmi\mlops\RAG_mlops25\rag\src\rag\d...,Harar och kaniner\n\nArtikel\nDiskussion\nLäs\...,"[-0.021514893, -0.024353027, 0.0044822693, -0...."
2,krabba.txt,C:\Users\tasmi\mlops\RAG_mlops25\rag\src\rag\d...,Krabbor (Brachyura) är en delordning av vatten...,"[0.011009216, -0.03277588, -0.049041748, -0.04..."
3,panda.txt,C:\Users\tasmi\mlops\RAG_mlops25\rag\src\rag\d...,"Jättepanda (Ailuropoda melanoleuca), panda, pa...","[0.07891846, 0.018447876, -0.00818634, -0.0604..."
4,tiger.txt,C:\Users\tasmi\mlops\RAG_mlops25\rag\src\rag\d...,Tiger (Panthera tigris) är ett kattdjur som en...,"[0.022979736, 0.03173828, -0.004386902, -0.050..."

In [4]:
db["articles"].search("vad äter pandor?").to_pandas()

,document_name,filepath,content,embedding,_distance
0,panda.txt,C:\Users\tasmi\mlops\RAG_mlops25\rag\src\rag\d...,"Jättepanda (Ailuropoda melanoleuca), panda, pa...","[0.07891846, 0.018447876, -0.00818634, -0.0604...",0.806009
1,krabba.txt,C:\Users\tasmi\mlops\RAG_mlops25\rag\src\rag\d...,Krabbor (Brachyura) är en delordning av vatten...,"[0.011009216, -0.03277588, -0.049041748, -0.04...",0.968804
2,tiger.txt,C:\Users\tasmi\mlops\RAG_mlops25\rag\src\rag\d...,Tiger (Panthera tigris) är ett kattdjur som en...,"[0.022979736, 0.03173828, -0.004386902, -0.050...",0.989742
3,fisk (1).txt,C:\Users\tasmi\mlops\RAG_mlops25\rag\src\rag\d...,Fiskar (Pisces) är en grupp vattenlevande rygg...,"[0.05697632, 0.020736694, -0.028640747, -0.049...",1.145227
4,kanin (1).txt,C:\Users\tasmi\mlops\RAG_mlops25\rag\src\rag\d...,Harar och kaniner\n\nArtikel\nDiskussion\nLäs\...,"[-0.021514893, -0.024353027, 0.0044822693, -0....",1.199942